#!/bin/bash

git submodule foreach git pull
git commit -a -m "updated webclient submodule"
git branch -D deploy
git checkout -b deploy
sed -i '/target\//d' .gitignore
./sbt clean compile stage
git add . -A
git commit -m "deploy"
git push -f openshift deploy:master
git checkout master
