#!/bin/bash

# get newest web-client
cd public
git checkout dev
git pull
cd ..

# pull and build server
branch=$(git rev-parse --abbrev-ref HEAD)
git branch -D deploy
git checkout -b deploy
cp gitignore_deploy .gitignore
./sbt clean compile stage
git add . -A
git commit -m "deploy"
git push -f openshift_stage deploy:master
git checkout $branch
