package constants

/**
 * User: Björn Reimer
 * Date: 30.10.14
 * Time: 14:45
 */

object ErrorCodes {

  type ErrorCodes = Seq[String]

  val ACCOUNT_MISSING_IDENTITY: ErrorCodes = Seq("ACCOUNT.MISSING.IDENTITY")

  val FILE_UPLOAD_QUOTA_EXCEEDED: ErrorCodes = Seq("FILE.UPLOAD.QUOTA.EXCEEDED")
  val FILE_UPLOAD_FILESIZE_EXCEEDED: ErrorCodes = Seq("FILE.UPLOAD.FILESIZE.EXCEEDED")

  val VERIFY_EXPIRED: ErrorCodes = Seq("VERIFY.EXPIRED")
  val VERIFY_VALUE_CHANGED: ErrorCodes = Seq("VERIFY.VALUE.CHANGED")

  val PASSWORD_RESET_EMAIL_NOT_FOUND: ErrorCodes = Seq("PASSWORD.RESET.EMAIL.NOT.FOUND")
  val PASSWORD_RESET_PHONENUMBER_NOT_FOUND: ErrorCodes = Seq("PASSWORD.RESET.PHONENUMBER.NOT.FOUND")
  val PASSWORD_RESET_LOGIN_NOT_FOUND: ErrorCodes = Seq("PASSWORD.RESET.LOGIN.NOT.FOUND")
  val PASSWORD_RESET_NO_EMAIL_OR_PHONENUMBER: ErrorCodes = Seq("PASSWORD.RESET.NO.EMAIL.PHONENUMBER")
  val PASSWORD_RESET_EXPIRED: ErrorCodes = Seq("PASSWORD.RESET.EXPIRED")

  val PHONENUMBER_INVALID: ErrorCodes = Seq("PHONENUMBER_INVALID")
  val EMAIL_INVALID: ErrorCodes = Seq("EMAIL_INVALID")

}
