package constants

/**
 * User: Björn Reimer
 * Date: 30.10.14
 * Time: 14:45
 */

object ErrorCodes {

  type ErrorCode = Option[String]

  val ACCOUNT_MISSING_IDENTITY: ErrorCode = Some("ACCOUNT.MISSING.IDENTITY")

  val FILE_UPLOAD_QUOTA_EXCEEDED: ErrorCode = Some("FILE.UPLOAD.QUOTA.EXCEEDED")
  val FILE_UPLOAD_FILESIZE_EXCEEDED: ErrorCode = Some("FILE.UPLOAD.FILESIZE.EXCEEDED")

  val VERIFY_EXPIRED: ErrorCode = Some("VERIFY.EXPIRED")
  val VERIFY_VALUE_CHANGED: ErrorCode = Some("VERIFY.VALUE.CHANGED")

  val PASSWORD_RESET_EMAIL_NOT_FOUND: ErrorCode = Some("PASSWORD.RESET.EMAIL.NOT.FOUND")
  val PASSWORD_RESET_PHONENUMBER_NOT_FOUND: ErrorCode = Some("PASSWORD.RESET.PHONENUMBER.NOT.FOUND")
  val PASSWORD_RESET_LOGIN_NOT_FOUND: ErrorCode = Some("PASSWORD.RESET.LOGIN.NOT.FOUND")
  val PASSWORD_RESET_NO_EMAIL_OR_PHONENUMBER: ErrorCode = Some("PASSWORD.RESET.NO.EMAIL.PHONENUMBER")
  val PASSWORD_RESET_EXPIRED: ErrorCode = Some("PASSWORD.RESET.EXPIRED")

}
